#!/usr/bin/env bash
# isntall nginx

apt update
apt -y install nginx
echo 'Holberton School' > /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
ufw allow 'Nginx HTTP'
service nginx start
