#!/usr/bin/env bash
# pokemon catch them all
echo "pgrep -f 100-process_and_pid_file" > /var/run/holbertonscript.pid
I=1
while [ $I ]
do
	trap "echo 'I hate the kill command'; rm '/var/run/holbertonscript.pid'; exit" SIGTERM
	trap "echo 'Y U no love me?!'" SIGINT
	trap "rm '/var/run/holbertonscript.pid'; exit" SIGQUIT
	echo "To infinity and beyond"
	sleep 2
done
