#!/usr/bin/env bash
I=1
while [ $I -lt 21 ]
do
	echo "$I"
	case $I in

	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	let I=I+1
done
