#!/usr/bin/env bash
# config localhost to 127.0.0.2 && facebook to 8.8.8.8
sudo cp /etc/hosts ~/tmp_file
sed -i "s/127.0.0.1/127.0.0.2/g" ~/tmp_file
echo "8.8.8.8 facebook.com" >> ~/tmp_file
sudo cp -f ~/tmp_file /etc/hosts
